apiVersion: v1
appVersion: 2.1.0
description: A Helm chart for Kubernetes
name: clamapi
home: https://github.com/cnieg/helm-charts/
sources:
  - https://github.com/audig/clamapi
version: 1.2.0
maintainers:
  - name: audig
