dependencies:
- name: elasticsearch
  version: 7.17.3
  repository: https://helm.elastic.co
  alias: master
- name: elasticsearch
  version: 7.17.3
  repository: https://helm.elastic.co
  alias: data
- name: elasticsearch
  version: 7.17.3
  repository: https://helm.elastic.co
  alias: client
- name: kibana
  version: 7.7.1
  repository: https://helm.elastic.co
  condition: kibana.enabled
- name: logstash
  version: 7.7.1
  repository: https://helm.elastic.co
  condition: logstash.enabled
- name: filebeat
  version: 7.7.1
  repository: https://helm.elastic.co
  condition: filebeat.enabled
