apiVersion: v2
name: castlemock
description: Castlemock webapp chart
type: application
version: 0.1.6
appVersion: latest
home: https://github.com/castlemock/castlemock
sources:
  - https://github.com/cnieg/helm-charts/tree/master/charts/castlemock
maintainers:
  - name: CNIEG
    email: maintainers@cnieg.fr
