apiVersion: v1
appVersion: "1.1.0"
description: A Helm chart for maildev
name: maildev
version: 1.1.1
home: https://github.com/maildev/maildev
sources:
  - https://github.com/maildev/maildev
icon: https://raw.githubusercontent.com/maildev/maildev/master/app/favicon.ico
maintainers:
  - name: audig
    email: maintainers@cnieg.fr
